-- MySQL Script generated by MySQL Workbench
-- Tue Sep  3 22:26:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Base de données EXPRESS FOOD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Base de données EXPRESS FOOD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Base de données EXPRESS FOOD` DEFAULT CHARACTER SET utf8 ;
USE `Base de données EXPRESS FOOD` ;

-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`client` (
  `client_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_client` VARCHAR(255) NOT NULL,
  `prenom_client` VARCHAR(255) NOT NULL,
  `numéro_tel_client` VARCHAR(20) NOT NULL,
  `mot_de_passe_client` VARCHAR(255) NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`adresse` (
  `adresse_id` INT(10) NOT NULL AUTO_INCREMENT,
  `numéro_rue` INT(10) UNSIGNED NOT NULL,
  `rue` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `code_Postal` INT(16) UNSIGNED NOT NULL,
  `etage` INT(11) NULL DEFAULT NULL,
  `batiment` VARCHAR(255) NULL DEFAULT NULL,
  `digicode` VARCHAR(10) NULL DEFAULT NULL,
  `client_id` INT(16) UNSIGNED NOT NULL,
  PRIMARY KEY (`adresse_id`),
  INDEX `fk_adresse_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_adresse_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`client` (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`livreur` (
  `livreur_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_livreur` VARCHAR(255) NOT NULL,
  `prenom_livreur` VARCHAR(255) NOT NULL,
  `telephone_livreur` VARCHAR(20) NOT NULL,
  `statut_livreur` VARCHAR(32) NOT NULL,
  `longitude` DECIMAL(8,6) UNSIGNED NULL DEFAULT NULL,
  `latitude` DECIMAL(8,6) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`livreur_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`panier` (
  `panier_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_panier` VARCHAR(255) NULL,
  PRIMARY KEY (`panier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`commande` (
  `commande_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_commande` DATE NULL DEFAULT NULL,
  `statut_commande` VARCHAR(32) NOT NULL,
  `heure_commande` TIME NULL DEFAULT NULL,
  `client_id` INT(10) UNSIGNED NOT NULL,
  `livreur_id` INT(11) NOT NULL,
  `panier_id` INT(11) NOT NULL,
  `adresse_livraison` INT(10) NOT NULL,
  PRIMARY KEY (`commande_id`),
  INDEX `fk_commande_client1_idx` (`client_id` ASC),
  INDEX `fk_commande_livreur1_idx` (`livreur_id` ASC),
  INDEX `fk_commande_panier1_idx` (`panier_id` ASC),
  INDEX `fk_commande_adresse1_idx` (`adresse_livraison` ASC),
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`client` (`client_id`),
  CONSTRAINT `fk_commande_livreur1`
    FOREIGN KEY (`livreur_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`livreur` (`livreur_id`),
  CONSTRAINT `fk_commande_panier1`
    FOREIGN KEY (`panier_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`panier` (`panier_id`),
  CONSTRAINT `fk_commande_adresse1`
    FOREIGN KEY (`adresse_livraison`)
    REFERENCES `Base de données EXPRESS FOOD`.`adresse` (`adresse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`plat_et_dessert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`plat_et_dessert` (
  `plat_et_dessert_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prix_unitaire` DECIMAL(3,2) NOT NULL,
  `type_plat` VARCHAR(32) NOT NULL,
  `photo` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`plat_et_dessert_id`),
  UNIQUE INDEX `nom_plat_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`commande_has_plat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`commande_has_plat` (
  `numero_commande_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `plat_et_dessert_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`numero_commande_id`, `plat_et_dessert_id`),
  INDEX `fk_commande_has_plat_plat1_idx` (`plat_et_dessert_id` ASC),
  INDEX `fk_commande_has_plat_commande1_idx` (`numero_commande_id` ASC),
  CONSTRAINT `fk_commande_has_plat_commande1`
    FOREIGN KEY (`numero_commande_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`commande` (`commande_id`),
  CONSTRAINT `fk_commande_has_plat_plat1`
    FOREIGN KEY (`plat_et_dessert_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`plat_et_dessert` (`plat_et_dessert_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`facture` (
  `numero_facture_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_facture` DATE NULL DEFAULT NULL,
  `montant_facture` DECIMAL(8,2) NULL,
  `commande_id` INT(10) UNSIGNED NOT NULL,
  `adresse_facture` INT(10) NOT NULL,
  PRIMARY KEY (`numero_facture_id`),
  INDEX `fk_facture_commande1_idx` (`commande_id` ASC),
  INDEX `fk_facture_adresse1_idx` (`adresse_facture` ASC),
  CONSTRAINT `fk_facture_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`commande` (`commande_id`),
  CONSTRAINT `fk_facture_adresse1`
    FOREIGN KEY (`adresse_facture`)
    REFERENCES `Base de données EXPRESS FOOD`.`adresse` (`adresse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Base de données EXPRESS FOOD`.`panier_has_plat_et_dessert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base de données EXPRESS FOOD`.`panier_has_plat_et_dessert` (
  `panier_id` INT(11) NOT NULL AUTO_INCREMENT,
  `plat_et_dessert_id` INT(10) UNSIGNED NOT NULL,
  `quantite` INT NULL,
  PRIMARY KEY (`panier_id`, `plat_et_dessert_id`),
  INDEX `fk_panier_has_plat_et_dessert_plat_et_dessert1_idx` (`plat_et_dessert_id` ASC),
  INDEX `fk_panier_has_plat_et_dessert_panier1_idx` (`panier_id` ASC),
  CONSTRAINT `fk_panier_has_plat_et_dessert_panier1`
    FOREIGN KEY (`panier_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`panier` (`panier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_has_plat_et_dessert_plat_et_dessert1`
    FOREIGN KEY (`plat_et_dessert_id`)
    REFERENCES `Base de données EXPRESS FOOD`.`plat_et_dessert` (`plat_et_dessert_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
